spring.application.name=backend

spring.mongodb.uri=mongodb://localhost:27017
spring.mongodb.database=nutriverse

server.port=8080

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=openai/gpt-oss-20b

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=${NEO4J_PASSWORD}